export const BOOTSTRAP = 'BOOTSTRAP';
export const PLUS_ONE = 'PLUS_ONE';
export const MINUS_ONE = 'MINUS_ONE';
export const GET_INTENT = 'GET_INTENT';
export const INTENT_ERROR = 'INTENT_ERROR';
export const SET_PHRASE = 'SET_PHRASE';

import { API_AI_ACCESS_TOKEN, API_AI_SUBSCRIPTION_KEY, API_AI_BASE_URL } from './secrets';

export { API_AI_ACCESS_TOKEN as API_AI_ACCESS_TOKEN };
export { API_AI_SUBSCRIPTION_KEY as API_AI_SUBSCRIPTION_KEY};
export { API_AI_BASE_URL as API_AI_BASE_URL};
